name: publish

permissions:
  contents: write
  pages: write          # <-- Add this line

on:
  push:
    branches:
      - main
jobs:
  release:
    name: publish
    runs-on: ubuntu-latest
    steps:
      - name: Enable actions unsecure commands
        run: |
          echo "ACTIONS_ALLOW_UNSECURE_COMMANDS=true" >> $GITHUB_ENV
      - name: Checkout The Code
        uses: actions/checkout@v2.1.1

      - name: Cache node_modules directory
        id: cache-modules
        uses: actions/cache@v1
        with:
          path: node_modules
          key: 12.x-${{ runner.OS }}-build-${{ hashFiles('package.json') }}

      - name: Install Package Dependenciess
        if: steps.cache-modules.outputs.cache-hit != 'true'
        run: yarn
      - name: Build the Package
        run: yarn build

      - name: Setup NodeJS
        uses: actions/setup-node@v1.4.2
        with:
          node-version: 12
          registry-url: https://registry.npmjs.org

      - name: Git Identity
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git remote set-url origin https://x-access-token:${GITHUB_TOKEN}@github.com/$GITHUB_REPOSITORY
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: update the module version
        run: npm version minor
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_AUTH_TOKEN}}
      - name: push version update to the repository
        run: git push origin main
      - name: publish the module to the node package manager #2
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_AUTH_TOKEN}}
